version: "3"

services:
  app_caixa_eletronico_test:
    build: .
    container_name: app_caixa_eletronico_test
    command: npm test
    environment:
      NODE_ENV: "test"
      APP_PORT: "3000"
    ports:
      - "3000:3000"
